"""Forms Builder product surface — FormDefinition ↔ Draft (C3).

P2.1 read model · P2.2 composition · P2.3 commands · P2.4 draft persistence.
C3: FormDefinition, draft state machine. No Adapter / publish / resolve.
"""

from __future__ import annotations

from backend.app.forms_platform.builder.commands import (
    BUILDER_COMPOSITION_COMMANDS_CONTRACT,
    add_instance,
    duplicate_instance,
    remove_instance,
    reorder_instance,
    replace_component_version,
    update_config,
)
from backend.app.forms_platform.builder.composition import (
    BUILDER_COMPOSITION_CONTRACT,
    CompositionInstance,
    CompositionIssue,
    FormDraftComposition,
    build_composition,
    build_instance,
    new_draft_id,
    new_instance_id,
    parse_composition,
)
from backend.app.forms_platform.builder.draft_persistence import (
    BUILDER_DRAFT_PERSISTENCE_CONTRACT,
    DraftRecord,
    InMemoryDraftStore,
    archive_draft,
    create_draft,
    get_draft,
    get_draft_revision,
    list_drafts,
    update_draft,
)
from backend.app.forms_platform.builder.definition import (
    BUILDER_DEFINITION_CONTRACT,
    FormDefinition,
)
from backend.app.forms_platform.builder.session import (
    BuilderSession,
    begin_save,
    close_session,
    complete_save,
    edit_session,
    fail_save_conflict,
    fail_save_validation,
    new_session,
    save_session,
    session_from_error,
)
from backend.app.forms_platform.builder.state import (
    BUILDER_STATES,
    MUTABLE_DRAFT_STATES,
    STATE_CLOSED,
    STATE_CONFLICT,
    STATE_DIRTY,
    STATE_NEW,
    STATE_SAVED,
    STATE_SAVING,
    STATE_VALIDATION_ERROR,
    transition,
)
from backend.app.forms_platform.builder.read_model import (
    BUILDER_READ_MODEL_CONTRACT,
    BuilderCategoryGroup,
    BuilderComponentView,
    BuilderConfigFieldView,
    BuilderPaletteItem,
    BuilderReadModel,
    builder_read_model,
)

__all__ = [
    "BUILDER_COMPOSITION_COMMANDS_CONTRACT",
    "BUILDER_COMPOSITION_CONTRACT",
    "BUILDER_DEFINITION_CONTRACT",
    "BUILDER_DRAFT_PERSISTENCE_CONTRACT",
    "BUILDER_READ_MODEL_CONTRACT",
    "BUILDER_STATES",
    "BuilderCategoryGroup",
    "BuilderComponentView",
    "BuilderConfigFieldView",
    "BuilderPaletteItem",
    "BuilderReadModel",
    "BuilderSession",
    "CompositionInstance",
    "CompositionIssue",
    "DraftRecord",
    "FormDefinition",
    "FormDraftComposition",
    "InMemoryDraftStore",
    "MUTABLE_DRAFT_STATES",
    "STATE_CLOSED",
    "STATE_CONFLICT",
    "STATE_DIRTY",
    "STATE_NEW",
    "STATE_SAVED",
    "STATE_SAVING",
    "STATE_VALIDATION_ERROR",
    "add_instance",
    "archive_draft",
    "begin_save",
    "build_composition",
    "build_instance",
    "builder_read_model",
    "close_session",
    "complete_save",
    "create_draft",
    "duplicate_instance",
    "edit_session",
    "fail_save_conflict",
    "fail_save_validation",
    "get_draft",
    "get_draft_revision",
    "list_drafts",
    "new_draft_id",
    "new_instance_id",
    "new_session",
    "parse_composition",
    "remove_instance",
    "reorder_instance",
    "replace_component_version",
    "save_session",
    "session_from_error",
    "transition",
    "update_config",
    "update_draft",
]
