[mypy]
python_version = 3.12
files = backend
ignore_missing_imports = True

# ВАЖНО: говорим mypy, что брать путь только от корня репо (.)
# и не использовать старые окружения, где бывает MYPYPATH=backend
mypy_path = .

# Требуем явных корней пакетов — убирает двусмысленность имен модулей
explicit_package_bases = True