import type { UiIconId } from '../platform/icons/uiIconPaths.generated'
import type { VisualAssetId } from '../platform/icons/visualAssets.generated'

export type SidebarIconSpec =
  | { kind: 'ui'; id: UiIconId }
  | { kind: 'platform'; id: VisualAssetId; variant?: 'brand' | 'default' | 'filled' }

/** Nav item key → HostFlow icon (Figma UI stroke or platform brand). */
export const SIDEBAR_ITEM_ICON: Partial<Record<string, SidebarIconSpec>> = {
  overview: { kind: 'ui', id: 'home' },
  analytics: { kind: 'ui', id: 'график' },
  'work-hub': { kind: 'ui', id: 'что-дальше' },
  'recruitment-searches': { kind: 'ui', id: 'подборы' },
  'recruitment-inbox': { kind: 'ui', id: 'отклики' },
  'hr-workspace': { kind: 'ui', id: 'сотрудники' },
  sales: { kind: 'ui', id: 'обращения' },
  marketing: { kind: 'ui', id: 'конверсия' },
  candidates: { kind: 'ui', id: 'candidates' },
  'candidates-no-next-action': { kind: 'ui', id: 'человек' },
  clients: { kind: 'ui', id: 'клиенты' },
  'do-procesowania': { kind: 'ui', id: 'filter' },
  vacancies: { kind: 'ui', id: 'подборы' },
  documents: { kind: 'ui', id: 'documents' },
  'service-orders': { kind: 'ui', id: 'заказы' },
  services: { kind: 'ui', id: 'услуги' },
  invoices: { kind: 'ui', id: 'инвойсы' },
  inbox: { kind: 'ui', id: 'отклики' },
  tasks: { kind: 'ui', id: 'мои-задачи' },
  'notification-alerts': { kind: 'ui', id: 'notifications' },
  calendar: { kind: 'ui', id: 'calendar' },
  'sla-incidents': { kind: 'ui', id: 'notifications' },
  'command-audit': { kind: 'ui', id: 'shield' },
  'leads-distribution': { kind: 'ui', id: 'передать' },
  'leads-distribution-rules': { kind: 'ui', id: 'передать' },
  'automation-rules': { kind: 'ui', id: 'автоматизации' },
  'automation-log': { kind: 'ui', id: 'история' },
  'acquisition-activity': { kind: 'ui', id: 'история' },
  automations: { kind: 'ui', id: 'автоматизации' },
  'integrations-meta': { kind: 'platform', id: 'meta', variant: 'brand' },
  'integrations-google': { kind: 'platform', id: 'google', variant: 'brand' },
  'integrations-webhook': { kind: 'platform', id: 'webhook', variant: 'default' },
  'settings-communications-messengers': { kind: 'ui', id: 'whatsapp' },
  'settings-communications-queue': { kind: 'ui', id: 'filter' },
  'settings-communications-sla': { kind: 'ui', id: 'часы' },
  'team-availability': { kind: 'ui', id: 'calendar' },
  'my-availability': { kind: 'ui', id: 'calendar' },
  'time-off': { kind: 'ui', id: 'отпуска' },
  leads: { kind: 'ui', id: 'отклики' },
  'my-company': { kind: 'ui', id: 'компания' },
  settings: { kind: 'ui', id: 'settings' },
  'settings-users': { kind: 'ui', id: 'пользователи' },
  'settings-billing': { kind: 'ui', id: 'платежи' },
  'settings-tenants': { kind: 'ui', id: 'клиенты' },
  'settings-funnels': { kind: 'ui', id: 'funnel' },
  'settings-docs': { kind: 'ui', id: 'documents' },
  'settings-candidate-profiles': { kind: 'ui', id: 'candidates' },
  'settings-custom-fields': { kind: 'ui', id: 'filter' },
  'settings-legal': { kind: 'ui', id: 'контракты' },
  'settings-company-access': { kind: 'ui', id: 'роли' },
  'settings-email': { kind: 'ui', id: 'email' },
  'settings-tenant-links': { kind: 'ui', id: 'интеграции' },
  'settings-integrations': { kind: 'ui', id: 'интеграции' },
  'settings-ruleset': { kind: 'ui', id: 'shield' },
  'settings-audit': { kind: 'ui', id: 'мониторинг' },
  'settings-communications': { kind: 'ui', id: 'email' },
  profile: { kind: 'ui', id: 'пользователи' },
}

export const SIDEBAR_DEFAULT_ICON: SidebarIconSpec = { kind: 'ui', id: 'мои-задачи' }
