"""initial schema

Revision ID: cd530c0f2042
Revises:
Create Date: 2025-09-02 12:35:09.303934+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "cd530c0f2042"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("country", sa.String(length=64), nullable=True),
        sa.Column("city", sa.String(length=128), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("contacts", sa.String(), nullable=True),
        sa.Column("extra", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_companies_name"), "companies", ["name"], unique=False)
    op.create_index(
        op.f("ix_companies_tenant_id"), "companies", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_companies_tenant_name", "companies", ["tenant_id", "name"], unique=False
    )
    op.create_table(
        "document_types",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("valid_days", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "code", name="uq_document_types_tenant_code"),
    )
    op.create_index(
        op.f("ix_document_types_tenant_id"),
        "document_types",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role", sa.Enum("viewer", "manager", "admin", name="role"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "vacancies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("salary_from", sa.String(length=32), nullable=True),
        sa.Column("salary_to", sa.String(length=32), nullable=True),
        sa.Column(
            "currency", sa.String(length=16), server_default="EUR", nullable=True
        ),
        sa.Column("extra", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.Enum("open", "closed", name="vacancystatus"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_vacancies_company_id", "vacancies", ["company_id"], unique=False
    )
    op.create_index("ix_vacancies_tenant_id", "vacancies", ["tenant_id"], unique=False)
    op.create_index("ix_vacancies_title", "vacancies", ["title"], unique=False)
    op.create_table(
        "candidate_vacancies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_id", sa.String(length=36), nullable=False),
        sa.Column("vacancy_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["vacancy_id"],
            ["vacancies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_candidate_vacancies_candidate_id"),
        "candidate_vacancies",
        ["candidate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_vacancies_status"),
        "candidate_vacancies",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_vacancies_tenant_id"),
        "candidate_vacancies",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_vacancies_vacancy_id"),
        "candidate_vacancies",
        ["vacancy_id"],
        unique=False,
    )
    op.create_index(
        "ix_candvac_tenant_cand_vac",
        "candidate_vacancies",
        ["tenant_id", "candidate_id", "vacancy_id"],
        unique=True,
    )
    op.create_table(
        "candidates",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("short_id", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("languages", sqlite.JSON(), nullable=True),
        sa.Column("stage", sa.String(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("manager", sa.String(), nullable=True),
        sa.Column("company_id", sa.String(), nullable=True),
        sa.Column("vacancy_id", sa.String(), nullable=True),
        sa.Column("docs_progress", sa.Text(), nullable=True),
        sa.Column("extra", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["vacancy_id"], ["vacancies.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_candidates_company_id"), "candidates", ["company_id"], unique=False
    )
    op.create_index(op.f("ix_candidates_email"), "candidates", ["email"], unique=False)
    op.create_index(
        op.f("ix_candidates_first_name"), "candidates", ["first_name"], unique=False
    )
    op.create_index(
        op.f("ix_candidates_last_name"), "candidates", ["last_name"], unique=False
    )
    op.create_index(
        op.f("ix_candidates_manager"), "candidates", ["manager"], unique=False
    )
    op.create_index(
        op.f("ix_candidates_short_id"), "candidates", ["short_id"], unique=False
    )
    op.create_index(op.f("ix_candidates_stage"), "candidates", ["stage"], unique=False)
    op.create_index(
        op.f("ix_candidates_tenant_id"), "candidates", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_candidates_vacancy_id"), "candidates", ["vacancy_id"], unique=False
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=True),
        sa.Column("path", sa.String(length=1024), nullable=True),
        sa.Column("issued_date", sa.Date(), nullable=True),
        sa.Column("expires_date", sa.Date(), nullable=True),
        sa.Column("reminder_days_before", sa.Integer(), nullable=False),
        sa.Column("extra", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_documents_candidate_id"), "documents", ["candidate_id"], unique=False
    )
    op.create_index(op.f("ix_documents_key"), "documents", ["key"], unique=False)
    op.create_index(
        "ix_documents_tenant_candidate_key",
        "documents",
        ["tenant_id", "candidate_id", "key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_documents_tenant_id"), "documents", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_documents_tenant_id"), table_name="documents")
    op.drop_index("ix_documents_tenant_candidate_key", table_name="documents")
    op.drop_index(op.f("ix_documents_key"), table_name="documents")
    op.drop_index(op.f("ix_documents_candidate_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_candidates_vacancy_id"), table_name="candidates")
    op.drop_index(op.f("ix_candidates_tenant_id"), table_name="candidates")
    op.drop_index(op.f("ix_candidates_stage"), table_name="candidates")
    op.drop_index(op.f("ix_candidates_short_id"), table_name="candidates")
    op.drop_index(op.f("ix_candidates_manager"), table_name="candidates")
    op.drop_index(op.f("ix_candidates_last_name"), table_name="candidates")
    op.drop_index(op.f("ix_candidates_first_name"), table_name="candidates")
    op.drop_index(op.f("ix_candidates_email"), table_name="candidates")
    op.drop_index(op.f("ix_candidates_company_id"), table_name="candidates")
    op.drop_table("candidates")
    op.drop_index("ix_candvac_tenant_cand_vac", table_name="candidate_vacancies")
    op.drop_index(
        op.f("ix_candidate_vacancies_vacancy_id"), table_name="candidate_vacancies"
    )
    op.drop_index(
        op.f("ix_candidate_vacancies_tenant_id"), table_name="candidate_vacancies"
    )
    op.drop_index(
        op.f("ix_candidate_vacancies_status"), table_name="candidate_vacancies"
    )
    op.drop_index(
        op.f("ix_candidate_vacancies_candidate_id"), table_name="candidate_vacancies"
    )
    op.drop_table("candidate_vacancies")
    op.drop_index("ix_vacancies_title", table_name="vacancies")
    op.drop_index("ix_vacancies_tenant_id", table_name="vacancies")
    op.drop_index("ix_vacancies_company_id", table_name="vacancies")
    op.drop_table("vacancies")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_document_types_tenant_id"), table_name="document_types")
    op.drop_table("document_types")
    op.drop_index("ix_companies_tenant_name", table_name="companies")
    op.drop_index(op.f("ix_companies_tenant_id"), table_name="companies")
    op.drop_index(op.f("ix_companies_name"), table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
