"""C2.2 Automation Engine — domain (Intent-only; no module imports / no send)."""

from backend.app.communications.automation.errors import AutomationDomainError
from backend.app.communications.automation.lifecycle import (
    archive_rule,
    assert_version_immutable_for_write,
    create_rule_with_draft,
    get_draft_version,
    get_latest_published_version,
    get_rule,
    publish_draft,
    record_decision,
    replace_draft_triggers,
    set_rule_enabled,
    update_draft_content,
)
from backend.app.models.communication_automation import (
    DECISION_OUTCOME_FIRE,
    DECISION_OUTCOME_SKIP,
    RECIPIENT_STRATEGIES,
    RULE_STATUS_ACTIVE,
    RULE_STATUS_ARCHIVED,
    VERSION_STATUS_DRAFT,
    VERSION_STATUS_PUBLISHED,
    AutomationDecision,
    AutomationRule,
    AutomationRuleVersion,
    AutomationTrigger,
    CommunicationAutomationDecision,
    CommunicationAutomationRule,
    CommunicationAutomationRuleVersion,
    CommunicationAutomationTrigger,
)

__all__ = [
    "AutomationDomainError",
    "CommunicationAutomationRule",
    "CommunicationAutomationRuleVersion",
    "CommunicationAutomationTrigger",
    "CommunicationAutomationDecision",
    "AutomationRule",
    "AutomationRuleVersion",
    "AutomationTrigger",
    "AutomationDecision",
    "RULE_STATUS_ACTIVE",
    "RULE_STATUS_ARCHIVED",
    "VERSION_STATUS_DRAFT",
    "VERSION_STATUS_PUBLISHED",
    "DECISION_OUTCOME_FIRE",
    "DECISION_OUTCOME_SKIP",
    "RECIPIENT_STRATEGIES",
    "create_rule_with_draft",
    "get_rule",
    "get_draft_version",
    "update_draft_content",
    "replace_draft_triggers",
    "publish_draft",
    "set_rule_enabled",
    "archive_rule",
    "get_latest_published_version",
    "record_decision",
    "assert_version_immutable_for_write",
]
