/**
 * Frozen G4 proof composition — typed records only.
 *
 * Next slice binds these onto ApplicationWorkspaceHost using the platform kit
 * (data types, fields, primitives, widgets, tables) — not page-local sections.
 * Notes/Consent are widgets in that kit, not the definition of the program.
 */

import type { WorkspaceContributionDefinition } from './contribution'

export const PROOF_CONSUMER_ID = 'recruitment_application' as const
export const PROOF_HOST_ID = 'application_workspace' as const

export const RECRUITMENT_APPLICATION_PROOF_CONTRIBUTIONS = [
  {
    class: 'shell_primitive',
    capability_id: 'identity',
    owner: 'recruitment_application',
    contributor: 'recruitment',
    host: 'application_workspace',
    consumer: 'recruitment_application',
    component_id: 'workspace.shell.identity',
    placement: { region: 'header' },
    ordering: 10,
    visibility: 'always',
    permissions: [],
    state_owner: 'recruitment_application',
    actions: [],
    events: [],
    license: 'default',
    conflicts: [],
  },
  {
    class: 'shell_primitive',
    capability_id: 'status',
    owner: 'recruitment_application',
    contributor: 'recruitment',
    host: 'application_workspace',
    consumer: 'recruitment_application',
    component_id: 'workspace.shell.status',
    placement: { region: 'header' },
    ordering: 20,
    visibility: 'always',
    permissions: [],
    state_owner: 'recruitment_application',
    actions: [],
    events: [],
    license: 'default',
    conflicts: [],
  },
  {
    class: 'shared_capability',
    capability_id: 'notes',
    owner: 'notes',
    contributor: 'notes',
    host: 'application_workspace',
    consumer: 'recruitment_application',
    component_id: 'workspace.shared.notes',
    placement: { region: 'overview' },
    ordering: 30,
    visibility: 'always',
    permissions: [],
    state_owner: 'notes',
    actions: [],
    events: [],
    license: 'default',
    conflicts: ['SalesInquiryCallNotesSection'],
  },
  {
    class: 'shared_capability',
    capability_id: 'consent',
    owner: 'compliance',
    contributor: 'compliance',
    host: 'application_workspace',
    consumer: 'recruitment_application',
    component_id: 'workspace.shared.consent',
    placement: { region: 'rail' },
    ordering: 40,
    visibility: 'always',
    permissions: [],
    state_owner: 'compliance',
    actions: [],
    events: [],
    license: 'default',
    conflicts: ['SalesInquiryRodoSection', 'CandidateRodoSection'],
  },
  {
    class: 'module_contribution',
    capability_id: 'recruitment.stage',
    owner: 'recruitment',
    contributor: 'recruitment',
    host: 'application_workspace',
    consumer: 'recruitment_application',
    component_id: 'workspace.module.recruitment.stage',
    placement: { region: 'decision' },
    ordering: 50,
    visibility: 'module_enabled',
    permissions: [],
    state_owner: 'recruitment',
    actions: [],
    events: [],
    license: 'default',
    conflicts: [],
  },
  {
    class: 'module_contribution',
    capability_id: 'recruitment.vacancy',
    owner: 'recruitment',
    contributor: 'recruitment',
    host: 'application_workspace',
    consumer: 'recruitment_application',
    component_id: 'workspace.module.recruitment.vacancy',
    placement: { region: 'rail' },
    ordering: 60,
    visibility: 'module_enabled',
    permissions: [],
    state_owner: 'recruitment',
    actions: [],
    events: [],
    license: 'default',
    conflicts: [],
  },
  {
    class: 'module_contribution',
    capability_id: 'recruitment.assignee',
    owner: 'recruitment',
    contributor: 'recruitment',
    host: 'application_workspace',
    consumer: 'recruitment_application',
    component_id: 'workspace.module.recruitment.assignee',
    placement: { region: 'rail' },
    ordering: 70,
    visibility: 'module_enabled',
    permissions: [],
    state_owner: 'recruitment',
    actions: [],
    events: [],
    license: 'default',
    conflicts: [],
  },
  {
    class: 'module_contribution',
    capability_id: 'fixture.optional_addon',
    owner: 'fixture',
    contributor: 'fixture',
    host: 'application_workspace',
    consumer: 'recruitment_application',
    component_id: 'workspace.fixture.optional_addon',
    placement: { region: 'rail' },
    ordering: 80,
    visibility: 'entitlement',
    permissions: [],
    state_owner: 'fixture',
    actions: [],
    events: [],
    license: 'optional',
    conflicts: [],
  },
] as const satisfies readonly WorkspaceContributionDefinition[]
