/**
 * GENERATED FILE — do not edit by hand.
 * Source: `shared/crm_app_paths.json`.
 * Regenerate: `python3 scripts/codegen/generate_crm_app_paths.py` or `npm run codegen:crm-app-paths`.
 */

export const CRM_APP_PATHS = {
  appShellPrefix: "/app",
  overview: "/app/overview",
  analytics: "/app/analytics",
  analyticsLeadConversionFunnel: "/app/analytics/lead-conversion",
  work: "/app/work",
  onboarding: "/app/onboarding/",
  onboardingCompany: "/app/onboarding/company",
  onboardingGettingStarted: "/app/onboarding/getting-started",
  onboardingWizard: "/app/onboarding/wizard",
  clientsDirectory: "/app/clients/directory",
  agencyClients: "/app/clients",
  clientsLinkBase: "/app/clients/link",
  hr: "/app/hr",
  hrEmployees: "/app/hr/employees",
  candidates: "/app/candidates",
  candidatesNoNextActionPage: "/app/candidates/no-next-action",
  candidateNew: "/app/candidates/new",
  pipeline: "/app/pipeline",
  vacancies: "/app/vacancies",
  vacancyNew: "/app/vacancies/new",
  leads: "/app/leads",
  leadsDistribution: "/app/leads/distribution",
  leadsDistributionRules: "/app/leads/distribution/rules",
  services: "/app/services",
  invoices: "/app/invoices",
  invoiceNew: "/app/invoices/new",
  orders: "/app/orders",
  documents: "/app/documents",
  procesowani: "/app/procesowani",
  tasks: "/app/work/tasks",
  workCalendar: "/app/work/calendar",
  automations: "/app/automations",
  automationAreaPrefix: "/app/automation",
  automationRules: "/app/automation-rules",
  automationLog: "/app/automation-log",
  inbox: "/app/inbox",
  /** Inbox with messages channel selected (legacy top-level /app/messages redirects here). */
  inboxMessagesScoped: "/app/inbox?channel=messages",
  inboxEmailScoped: "/app/inbox?channel=email",
  inboxThreadsBase: "/app/inbox/threads",
  calendar: "/app/calendar",
  /** Legacy: top-level /app/messages — redirects into Inbox with channel=messages. */
  messages: "/app/messages",
  email: "/app/email",
  fleet: "/app/fleet",
  fleetVehicles: "/app/fleet/vehicles",
  fleetTrailers: "/app/fleet/trailers",
  fleetDrivers: "/app/fleet/drivers",
  fleetCounterparties: "/app/fleet/counterparties",
  fleetAssignments: "/app/fleet/assignments",
  fleetOperatingLines: "/app/fleet/operating-lines",
  fleetHrBridge: "/app/fleet/hr-bridge",
  fleetRotation: "/app/fleet/rotation",
  fleetCalendar: "/app/fleet/calendar",
  fleetTelematics: "/app/fleet/telematics",
  fleetTachograph: "/app/fleet/tachograph",
  fleetViolations: "/app/fleet/violations",
  fleetPayroll: "/app/fleet/payroll",
  fleetReports: "/app/fleet/reports",
  fleetReconciliation: "/app/fleet/reconciliation",
  fleetSettings: "/app/fleet/settings",
  setupCommunications: "/app/setup/communications",
  slaIncidents: "/app/sla-incidents",
  communicationsCommandAudit: "/app/communications/command-audit",
  communicationsThreadsBase: "/app/communications/threads",
  /** Legacy aggregate URL kept for redirects/bookmarks. */
  communicationsLegacyHub: "/app/communications",
  profile: "/app/profile",
  myCompany: "/app/my-company",
  myAvailability: "/app/my-availability",
  teamAvailability: "/app/team-availability",
  timeOff: "/app/time-off",
  clientNew: "/app/clients/new",
  companiesOperatingBilling: "/app/my-company?section=billing",
  settings: "/app/settings",
  settingsUsers: "/app/settings/users",
  settingsBilling: "/app/settings/billing",
  settingsBillingPlan: "/app/settings/billing/plan",
  settingsLegal: "/app/settings/legal",
  settingsCompanyAccess: "/app/settings/company-access",
  settingsFunnels: "/app/settings/funnels",
  settingsEmail: "/app/settings/email",
  settingsTenantLinks: "/app/settings/tenant-links",
  settingsIntegrations: "/app/settings/integrations",
  settingsIntegrationsMeta: "/app/settings/integrations/meta",
  settingsIntegrationsGoogle: "/app/settings/integrations/google",
  /** Facebook Messenger channel under Integration hub (URL segment repeats API channel key “messenger”). */
  settingsIntegrationsMessengerFacebook: "/app/settings/integrations/messenger/messenger",
  settingsIntegrationsMessengerInstagram: "/app/settings/integrations/messenger/instagram",
  settingsIntegrationsMessengerTelegram: "/app/settings/integrations/messenger/telegram",
  settingsIntegrationsMessengerViber: "/app/settings/integrations/messenger/viber",
  settingsIntegrationsMessengerWhatsapp: "/app/settings/integrations/messenger/whatsapp",
  settingsIntegrationsWebhook: "/app/settings/integrations/webhook",
  settingsAudit: "/app/settings/audit",
  settingsCommunications: "/app/settings/communications",
  settingsCommunicationsMessengers: "/app/settings/communications/messengers",
  settingsCommunicationsQueue: "/app/settings/communications/queue",
  settingsCommunicationsSla: "/app/settings/communications/sla",
  settingsTeam: "/app/settings/team",
  settingsRiskIntel: "/app/settings/risk-intel",
  settingsHiringPipelineGates: "/app/settings/hiring-pipeline-gates",
  settingsRuleset: "/app/settings/ruleset",
  settingsDocs: "/app/settings/docs",
  settingsMergeTemplates: "/app/settings/document-merge-templates",
  settingsTenants: "/app/settings/tenants",
  /** Legacy aliased Meta / lead-source admin (canonical: settingsIntegrationsMeta). */
  settingsLeads: "/app/settings/leads",
  settingsLeadForms: "/app/settings/lead-forms",
  settingsTtvReport: "/app/settings/ttv-report",
  settingsCandidateProfiles: "/app/settings/candidate-profiles",
  settingsCustomFields: "/app/settings/custom-fields",
  /** Legacy URLs kept for redirects / bookmarks. */
  companiesLegacy: "/app/companies",
  doProcesowaniaLegacy: "/app/do-procesowania",
  /** Legacy planner shell — redirects to /app/calendar (Phase 2.1 absorbed planner into Activity). */
  plannerLegacy: "/app/planner",
  remindersLegacy: "/app/reminders",
  activitiesLegacy: "/app/activities",
} as const

export const CRM_APP_DRILLDOWN_HREFS = {
  vacanciesOpen: "/app/vacancies?status=open",
  ordersOpen: "/app/orders?status=open",
  invoicesOverdueUnpaid: "/app/invoices?queue=overdue_unpaid",
  tasksOverdueReminders: "/app/work/tasks?tab=tasks&t_status=active&t_due_bucket=overdue",
  tasksLeadsSlaNudges: "/app/work/tasks?tab=tasks&t_status=active&t_entity=lead",
  tasksCandidateOverdueNextAction: "/app/work/tasks?tab=tasks&t_status=active&t_entity=candidate",
  leadsNeedsRouting: "/app/leads?status=needs_routing",
  leadsFailed: "/app/leads?status=failed",
  leadsProcessedNoNextAction: "/app/leads?status=processed&next_action=no_next_action",
  leadsProcessedStuck: "/app/leads?status=processed&next_action=stuck",
  candidatesDraftIntakeDebug: "/app/candidates?debug=1",
  /** Main candidates list with no-next-action queue (see CandidatesListGate). */
  candidatesQueueNoNextAction: "/app/candidates?queue=no_next_action",
  /** Candidates list filtered to stage «employment_pending» (HR paperwork in progress). */
  candidatesStageEmploymentPending: "/app/candidates?qv=employment_pending",
} as const
