/**
 * GENERATED FILE — do not edit by hand.
 * Source: `shared/crm_app_paths.json`.
 * Regenerate: `python3 scripts/codegen/generate_crm_app_paths.py` or `npm run codegen:crm-app-paths`.
 */

export const CRM_APP_PATHS = {
  appShellPrefix: "/app",
  overview: "/app/overview",
  analytics: "/app/analytics",
  analyticsLeadConversionFunnel: "/app/analytics/lead-conversion",
  work: "/app/work",
  onboarding: "/app/onboarding/",
  onboardingCompany: "/app/onboarding/company",
  onboardingGettingStarted: "/app/onboarding/getting-started",
  onboardingWizard: "/app/onboarding/wizard",
  clientsDirectory: "/app/clients/directory",
  agencyClients: "/app/clients",
  clientsLinkBase: "/app/clients/link",
  hr: "/app/hr",
  /** Internal HR inbox (handoffs); uses /api/v1/hr/* only. */
  hrInbox: "/app/hr/inbox",
  /** HR lane reminder tasks; uses /api/v1/hr/tasks. */
  hrTasks: "/app/hr/tasks",
  /** HR compliance document queues; uses /api/v1/hr/documents/*. */
  hrCompliance: "/app/hr/compliance",
  hrDocuments: "/app/hr/documents",
  hrDocumentsMissing: "/app/hr/documents/missing",
  hrDocumentsExpiring: "/app/hr/documents/expiring",
  hrDocumentsVerification: "/app/hr/documents/verification",
  /** ZUS operational workspace; uses /api/v1/workforce/zus-workspace/*. */
  hrZusWorkspace: "/app/hr/zus-workspace",
  /** Handoff detail + snapshot under HR workspace shell. */
  hrHandoffs: "/app/hr/handoffs",
  hrEmployees: "/app/hr/employees",
  candidates: "/app/candidates",
  candidatesNoNextActionPage: "/app/candidates/no-next-action",
  candidateNew: "/app/candidates/new",
  pipeline: "/app/pipeline",
  vacancies: "/app/vacancies",
  vacancyNew: "/app/vacancies/new",
  leads: "/app/leads",
  leadsDistribution: "/app/leads/distribution",
  leadsDistributionRules: "/app/leads/distribution/rules",
  /** Operational sales workspace for services tenants (inquiries, work session, conversion). */
  sales: "/app/sales",
  /** Sales Service Orders (ADR-032 commercial deal + order lines). Not Services-module /app/orders. */
  salesOrders: "/app/sales/orders",
  launchpad: "/app/launchpad",
  /** Client acquisition channel list and per-channel inquiry workspace. */
  clientAcquisitionChannels: "/app/client-acquisition/channels",
  clientAcquisitionChannelsNew: "/app/client-acquisition/channels/new",
  services: "/app/services",
  invoices: "/app/invoices",
  invoiceNew: "/app/invoices/new",
  orders: "/app/orders",
  documents: "/app/documents",
  procesowani: "/app/procesowani",
  tasks: "/app/work/tasks",
  workCalendar: "/app/work/calendar",
  automations: "/app/automations",
  automationAreaPrefix: "/app/automation",
  automationRules: "/app/automation-rules",
  automationLog: "/app/automation-log",
  /** Stage 3E read-only Acquisition Activity Timeline (platform campaigns). */
  acquisitionActivity: "/app/acquisition/activity",
  /** Marketing Workspace — campaign list and Flight operator surface (Acquisition capability UI). */
  marketing: "/app/marketing",
  /** Create Campaign only (goal + Primary Target + optional context). Sources connect separately via spa_marketing_connect_source. */
  marketingNew: "/app/marketing/new",
  /** Marketing Sources foundation — intake inventory, connection, Mapping Health (C-3). */
  marketingSources: "/app/marketing/sources",
  /** Marketing Forms — HostFlow Form Builder remount (C-6); SoT remains ADR-007 / settings APIs. */
  marketingForms: "/app/marketing/forms",
  inbox: "/app/inbox",
  /** Inbox with messages channel selected (legacy top-level /app/messages redirects here). */
  inboxMessagesScoped: "/app/inbox?channel=messages",
  inboxEmailScoped: "/app/inbox?channel=email",
  inboxThreadsBase: "/app/inbox/threads",
  calendar: "/app/calendar",
  /** Legacy: top-level /app/messages — redirects into Inbox with channel=messages. */
  messages: "/app/messages",
  email: "/app/email",
  fleet: "/app/fleet",
  fleetVehicles: "/app/fleet/vehicles",
  fleetTrailers: "/app/fleet/trailers",
  fleetDrivers: "/app/fleet/drivers",
  fleetCounterparties: "/app/fleet/counterparties",
  fleetAssignments: "/app/fleet/assignments",
  fleetOperatingLines: "/app/fleet/operating-lines",
  fleetHrBridge: "/app/fleet/hr-bridge",
  fleetRotation: "/app/fleet/rotation",
  fleetCalendar: "/app/fleet/calendar",
  fleetTelematics: "/app/fleet/telematics",
  fleetTachograph: "/app/fleet/tachograph",
  fleetViolations: "/app/fleet/violations",
  fleetPayroll: "/app/fleet/payroll",
  fleetReports: "/app/fleet/reports",
  fleetReconciliation: "/app/fleet/reconciliation",
  fleetSettings: "/app/fleet/settings",
  setupCommunications: "/app/setup/communications",
  slaIncidents: "/app/sla-incidents",
  notificationAlerts: "/app/notifications/alerts",
  communicationsCommandAudit: "/app/communications/command-audit",
  communicationsThreadsBase: "/app/communications/threads",
  /** Legacy aggregate URL kept for redirects/bookmarks. */
  communicationsLegacyHub: "/app/communications",
  profile: "/app/profile",
  /** Tenant organization hub — subscription, modules, users, operating companies list (not OwnCompany legal profile). */
  organization: "/app/organization",
  myCompany: "/app/my-company",
  myAvailability: "/app/my-availability",
  teamAvailability: "/app/team-availability",
  timeOff: "/app/time-off",
  clientNew: "/app/clients/new",
  /** Deep-link to OwnCompany bank tab (issuer bank/legal data). Tenant subscription lives at organization / settingsBilling — do not reuse this for plan billing. */
  companiesOperatingBilling: "/app/my-company?tab=bank",
  settings: "/app/settings",
  settingsUsers: "/app/settings/users",
  settingsBilling: "/app/settings/billing",
  settingsBillingPlan: "/app/settings/billing/plan",
  settingsLegal: "/app/settings/legal",
  settingsCompanyAccess: "/app/settings/company-access",
  settingsFunnels: "/app/settings/funnels",
  settingsEmail: "/app/settings/email",
  settingsTenantLinks: "/app/settings/tenant-links",
  settingsIntegrations: "/app/settings/integrations",
  settingsIntegrationsMeta: "/app/settings/integrations/meta",
  settingsIntegrationsGoogle: "/app/settings/integrations/google",
  /** Facebook Messenger channel under Integration hub (URL segment repeats API channel key “messenger”). */
  settingsIntegrationsMessengerFacebook: "/app/settings/integrations/messenger/messenger",
  settingsIntegrationsMessengerInstagram: "/app/settings/integrations/messenger/instagram",
  settingsIntegrationsMessengerTelegram: "/app/settings/integrations/messenger/telegram",
  settingsIntegrationsMessengerViber: "/app/settings/integrations/messenger/viber",
  settingsIntegrationsMessengerWhatsapp: "/app/settings/integrations/messenger/whatsapp",
  settingsIntegrationsWebhook: "/app/settings/integrations/webhook",
  settingsAudit: "/app/settings/audit",
  settingsCommunications: "/app/settings/communications",
  settingsCommunicationsMessengers: "/app/settings/communications/messengers",
  settingsCommunicationsQueue: "/app/settings/communications/queue",
  settingsCommunicationsSla: "/app/settings/communications/sla",
  settingsCommunicationsTemplates: "/app/settings/communications/templates",
  settingsCommunicationsAutomation: "/app/settings/communications/automation",
  settingsCommunicationsLeadLifecycleEmail: "/app/settings/communications/lead-lifecycle-email",
  settingsCommunicationsCampaigns: "/app/settings/communications/campaigns",
  settingsTeam: "/app/settings/team",
  settingsRiskIntel: "/app/settings/risk-intel",
  settingsHiringPipelineGates: "/app/settings/hiring-pipeline-gates",
  settingsTransferPolicy: "/app/settings/transfer-policy",
  settingsRuleset: "/app/settings/ruleset",
  settingsDocs: "/app/settings/docs",
  settingsMergeTemplates: "/app/settings/document-merge-templates",
  settingsTenants: "/app/settings/tenants",
  /** Legacy aliased Meta / lead-source admin (canonical: settingsIntegrationsMeta). */
  settingsLeads: "/app/settings/leads",
  settingsMessageTemplates: "/app/settings/message-templates",
  settingsLeadForms: "/app/settings/lead-forms",
  settingsTtvReport: "/app/settings/ttv-report",
  settingsCandidateProfiles: "/app/settings/candidate-profiles",
  settingsCustomFields: "/app/settings/custom-fields",
  /** Legacy URLs kept for redirects / bookmarks. */
  companiesLegacy: "/app/companies",
  doProcesowaniaLegacy: "/app/do-procesowania",
  /** Legacy planner shell — redirects to /app/calendar (Phase 2.1 absorbed planner into Activity). */
  plannerLegacy: "/app/planner",
  remindersLegacy: "/app/reminders",
  activitiesLegacy: "/app/activities",
  recruitmentSearches: "/app/recruitment/searches",
  recruitmentSearchesNew: "/app/recruitment/searches/new",
  recruitmentInbox: "/app/recruitment/inbox",
  setup: "/app/setup",
  setupClient: "/app/setup/client",
  setupVacancy: "/app/setup/vacancy",
  setupProcess: "/app/setup/process",
  setupIntake: "/app/setup/intake",
  platformSetup: "/app/platform/setup",
  /** Marketing Source Diagnostics — ops console for recent submissions (post Ad-ID bind UI). */
  marketingDiagnostics: "/app/marketing/diagnostics",
} as const

export const CRM_APP_DRILLDOWN_HREFS = {
  vacanciesOpen: "/app/vacancies?status=open",
  ordersOpen: "/app/orders?status=open",
  invoicesOverdueUnpaid: "/app/invoices?queue=overdue_unpaid",
  tasksOverdueReminders: "/app/work/tasks?tab=tasks&t_status=active&t_due_bucket=overdue",
  tasksLeadsSlaNudges: "/app/work/tasks?tab=tasks&t_status=active&t_entity=lead",
  tasksCandidateOverdueNextAction: "/app/work/tasks?tab=tasks&t_status=active&t_entity=candidate",
  leadsNeedsRouting: "/app/leads?status=needs_routing",
  leadsFailed: "/app/leads?status=failed",
  leadsProcessedNoNextAction: "/app/leads?status=processed&next_action=no_next_action",
  leadsProcessedStuck: "/app/leads?status=processed&next_action=stuck",
  candidatesDraftIntakeDebug: "/app/candidates?debug=1",
  /** Main candidates list with no-next-action queue (see CandidatesListGate). */
  candidatesQueueNoNextAction: "/app/candidates?queue=no_next_action",
  /** Candidates list — ready for handoff quick view (recruitment queue before HR). */
  candidatesStageEmploymentPending: "/app/candidates?qv=ready_for_handoff",
} as const
