/**
 * GENERATED FILE — do not edit by hand.
 * Source: `shared/figma_icon_index.json`.
 * Regenerate: `python3 scripts/codegen/generate_ui_icons.py`
 */


export type UiIconSection = "actions" | "analytics" | "attachments" | "automation" | "candidate-hr" | "communication" | "documents" | "filters" | "fleet" | "navigation-main-menu" | "notifications" | "priority" | "sales" | "source-icons" | "status" | "system" | "time" | "workflow"

export type UiIconKey = "actions/архивировать" | "actions/далее" | "actions/дублировать" | "actions/загрузить" | "actions/закрыть" | "actions/импорт" | "actions/копировать" | "actions/назад" | "actions/обновить" | "actions/открыть" | "actions/печать" | "actions/поделиться" | "actions/редактировать" | "actions/скачать" | "actions/создать" | "actions/сохранить" | "actions/удалить" | "actions/экспорт" | "analytics/funnel" | "analytics/kpi" | "analytics/график" | "analytics/конверсия" | "analytics/падение" | "analytics/рост" | "analytics/статистика" | "attachments/excel" | "attachments/pdf" | "attachments/word" | "attachments/zip" | "attachments/видео" | "attachments/облако" | "attachments/ссылка" | "attachments/фото" | "automation/ai" | "automation/workflow" | "automation/автоматизация" | "automation/интеграция" | "automation/робот" | "automation/триггер" | "candidate-hr/адрес" | "candidate-hr/гражданство" | "candidate-hr/дата-рожд" | "candidate-hr/кат-прав" | "candidate-hr/навыки" | "candidate-hr/образование" | "candidate-hr/опыт" | "candidate-hr/пол" | "candidate-hr/разрешение" | "candidate-hr/семья" | "candidate-hr/человек" | "candidate-hr/язык" | "communication/email" | "communication/messenger" | "communication/sms" | "communication/telegram" | "communication/whatsapp" | "communication/видео-звонок" | "communication/запись-звонка" | "communication/история" | "communication/позвонить" | "documents/id-карта" | "documents/ocr" | "documents/pdf" | "documents/архив" | "documents/виза" | "documents/внж" | "documents/документ" | "documents/карта-побыту" | "documents/код-95" | "documents/медосмотр" | "documents/паспорт" | "documents/подпись" | "documents/права-вод" | "documents/психотест" | "documents/сертификат" | "documents/фото" | "filters/filter" | "filters/search" | "filters/вид" | "filters/группировка" | "filters/канбан" | "filters/колонки" | "filters/сбросить" | "filters/сортировка" | "filters/сохр-вид" | "filters/список" | "filters/таблица" | "fleet/gps" | "fleet/авария" | "fleet/автобус" | "fleet/грузовик" | "fleet/карта" | "fleet/ключ" | "fleet/колесо" | "fleet/легковой" | "fleet/маршрут" | "fleet/прицеп" | "fleet/пробег" | "fleet/сервис-то" | "fleet/топливо" | "navigation-main-menu/api" | "navigation-main-menu/calendar" | "navigation-main-menu/candidates" | "navigation-main-menu/documents" | "navigation-main-menu/home" | "navigation-main-menu/notifications" | "navigation-main-menu/settings" | "navigation-main-menu/автоматизации" | "navigation-main-menu/автомобили" | "navigation-main-menu/водители" | "navigation-main-menu/доходы" | "navigation-main-menu/заказы" | "navigation-main-menu/инвойсы" | "navigation-main-menu/интеграции" | "navigation-main-menu/клиенты" | "navigation-main-menu/контракты" | "navigation-main-menu/легализация" | "navigation-main-menu/медосмотры" | "navigation-main-menu/мои-задачи" | "navigation-main-menu/мониторинг" | "navigation-main-menu/обращения" | "navigation-main-menu/обучение" | "navigation-main-menu/отделы" | "navigation-main-menu/отклики" | "navigation-main-menu/отпуска" | "navigation-main-menu/отсутствия" | "navigation-main-menu/платежи" | "navigation-main-menu/подборы" | "navigation-main-menu/поломки" | "navigation-main-menu/пользователи" | "navigation-main-menu/прицепы" | "navigation-main-menu/расходы" | "navigation-main-menu/роли" | "navigation-main-menu/сотрудники" | "navigation-main-menu/счета" | "navigation-main-menu/тахографы" | "navigation-main-menu/то" | "navigation-main-menu/топливо" | "navigation-main-menu/услуги" | "navigation-main-menu/что-дальше" | "navigation-main-menu/шины" | "notifications/информация" | "notifications/колокол" | "notifications/напоминание" | "notifications/ошибка" | "notifications/предупреждение" | "notifications/успех" | "priority/critical" | "priority/high" | "priority/low" | "priority/medium" | "sales/деньги" | "sales/договор" | "sales/клиент-vip" | "sales/компания" | "sales/контакт" | "sales/кп" | "sales/оплата" | "sales/подписание" | "sales/сделка" | "sales/услуга" | "source-icons/api-source" | "source-icons/crm" | "source-icons/csv" | "source-icons/email" | "source-icons/facebook" | "source-icons/google-ads" | "source-icons/google-maps" | "source-icons/google-search" | "source-icons/import-file" | "source-icons/instagram" | "source-icons/internal" | "source-icons/landing-page" | "source-icons/linkedin" | "source-icons/manual" | "source-icons/messenger" | "source-icons/meta" | "source-icons/phone" | "source-icons/qr-code" | "source-icons/recommendation" | "source-icons/referral" | "source-icons/sms" | "source-icons/telegram" | "source-icons/tiktok" | "source-icons/viber" | "source-icons/website" | "source-icons/whatsapp" | "source-icons/youtube" | "status/архив" | "status/в-работе" | "status/важно" | "status/заблокировано" | "status/завершено" | "status/новый" | "status/ожидает" | "status/ошибка" | "status/просрочено" | "status/черновик" | "system/api" | "system/company" | "system/database" | "system/module" | "system/security" | "system/shield" | "system/sync" | "system/tenant" | "system/workspace" | "system/мониторинг" | "system/пользователь" | "time/calendar" | "time/завтра" | "time/история" | "time/просрочено" | "time/сегодня" | "time/таймер" | "time/часы" | "workflow/выполнено" | "workflow/заблокировано" | "workflow/конвертировать" | "workflow/на-проверке" | "workflow/назначить" | "workflow/ожидание" | "workflow/отклонено" | "workflow/передать" | "workflow/подтверждено" | "workflow/следующий-шаг" | "workflow/требует-внимания"

export type UiIconAliasId = "ai" | "api" | "api-source" | "calendar" | "candidates" | "company" | "critical" | "crm" | "csv" | "database" | "documents" | "email" | "excel" | "facebook" | "filter" | "funnel" | "google-ads" | "google-maps" | "google-search" | "gps" | "high" | "home" | "id-карта" | "import-file" | "instagram" | "internal" | "kpi" | "landing-page" | "linkedin" | "low" | "manual" | "medium" | "messenger" | "meta" | "module" | "notifications" | "ocr" | "pdf" | "phone" | "qr-code" | "recommendation" | "referral" | "search" | "security" | "settings" | "shield" | "sms" | "sync" | "telegram" | "tenant" | "tiktok" | "viber" | "website" | "whatsapp" | "word" | "workflow" | "workspace" | "youtube" | "zip" | "авария" | "автобус" | "автоматизации" | "автоматизация" | "автомобили" | "адрес" | "архив" | "архивировать" | "в-работе" | "важно" | "вид" | "видео" | "видео-звонок" | "виза" | "внж" | "водители" | "выполнено" | "гражданство" | "график" | "грузовик" | "группировка" | "далее" | "дата-рожд" | "деньги" | "договор" | "документ" | "доходы" | "дублировать" | "заблокировано" | "завершено" | "завтра" | "загрузить" | "заказы" | "закрыть" | "запись-звонка" | "импорт" | "инвойсы" | "интеграции" | "интеграция" | "информация" | "история" | "канбан" | "карта" | "карта-побыту" | "кат-прав" | "клиент-vip" | "клиенты" | "ключ" | "код-95" | "колесо" | "колокол" | "колонки" | "компания" | "конверсия" | "конвертировать" | "контакт" | "контракты" | "копировать" | "кп" | "легализация" | "легковой" | "маршрут" | "медосмотр" | "медосмотры" | "мои-задачи" | "мониторинг" | "на-проверке" | "навыки" | "назад" | "назначить" | "напоминание" | "новый" | "облако" | "обновить" | "образование" | "обращения" | "обучение" | "ожидает" | "ожидание" | "оплата" | "опыт" | "отделы" | "отклики" | "отклонено" | "открыть" | "отпуска" | "отсутствия" | "ошибка" | "падение" | "паспорт" | "передать" | "печать" | "платежи" | "подборы" | "поделиться" | "подписание" | "подпись" | "подтверждено" | "позвонить" | "пол" | "поломки" | "пользователи" | "пользователь" | "права-вод" | "предупреждение" | "прицеп" | "прицепы" | "пробег" | "просрочено" | "психотест" | "разрешение" | "расходы" | "редактировать" | "робот" | "роли" | "рост" | "сбросить" | "сделка" | "сегодня" | "семья" | "сервис-то" | "сертификат" | "скачать" | "следующий-шаг" | "создать" | "сортировка" | "сотрудники" | "сохр-вид" | "сохранить" | "список" | "ссылка" | "статистика" | "счета" | "таблица" | "таймер" | "тахографы" | "то" | "топливо" | "требует-внимания" | "триггер" | "удалить" | "услуга" | "услуги" | "успех" | "фото" | "часы" | "человек" | "черновик" | "что-дальше" | "шины" | "экспорт" | "язык"

export type UiIconId = UiIconKey | UiIconAliasId

export type UiIconRecord = {
  key: UiIconKey
  id: string
  section: UiIconSection
  label: string
}

export const UI_ICONS = {
  "actions/архивировать": { key: "actions/архивировать", id: "архивировать", section: "actions", label: "Архивировать" },
  "actions/далее": { key: "actions/далее", id: "далее", section: "actions", label: "Далее" },
  "actions/дублировать": { key: "actions/дублировать", id: "дублировать", section: "actions", label: "Дублировать" },
  "actions/загрузить": { key: "actions/загрузить", id: "загрузить", section: "actions", label: "Загрузить" },
  "actions/закрыть": { key: "actions/закрыть", id: "закрыть", section: "actions", label: "Закрыть" },
  "actions/импорт": { key: "actions/импорт", id: "импорт", section: "actions", label: "Импорт" },
  "actions/копировать": { key: "actions/копировать", id: "копировать", section: "actions", label: "Копировать" },
  "actions/назад": { key: "actions/назад", id: "назад", section: "actions", label: "Назад" },
  "actions/обновить": { key: "actions/обновить", id: "обновить", section: "actions", label: "Обновить" },
  "actions/открыть": { key: "actions/открыть", id: "открыть", section: "actions", label: "Открыть" },
  "actions/печать": { key: "actions/печать", id: "печать", section: "actions", label: "Печать" },
  "actions/поделиться": { key: "actions/поделиться", id: "поделиться", section: "actions", label: "Поделиться" },
  "actions/редактировать": { key: "actions/редактировать", id: "редактировать", section: "actions", label: "Редактировать" },
  "actions/скачать": { key: "actions/скачать", id: "скачать", section: "actions", label: "Скачать" },
  "actions/создать": { key: "actions/создать", id: "создать", section: "actions", label: "Создать" },
  "actions/сохранить": { key: "actions/сохранить", id: "сохранить", section: "actions", label: "Сохранить" },
  "actions/удалить": { key: "actions/удалить", id: "удалить", section: "actions", label: "Удалить" },
  "actions/экспорт": { key: "actions/экспорт", id: "экспорт", section: "actions", label: "Экспорт" },
  "analytics/funnel": { key: "analytics/funnel", id: "funnel", section: "analytics", label: "Funnel" },
  "analytics/kpi": { key: "analytics/kpi", id: "kpi", section: "analytics", label: "KPI" },
  "analytics/график": { key: "analytics/график", id: "график", section: "analytics", label: "График" },
  "analytics/конверсия": { key: "analytics/конверсия", id: "конверсия", section: "analytics", label: "Конверсия" },
  "analytics/падение": { key: "analytics/падение", id: "падение", section: "analytics", label: "Падение" },
  "analytics/рост": { key: "analytics/рост", id: "рост", section: "analytics", label: "Рост" },
  "analytics/статистика": { key: "analytics/статистика", id: "статистика", section: "analytics", label: "Статистика" },
  "attachments/excel": { key: "attachments/excel", id: "excel", section: "attachments", label: "Excel" },
  "attachments/pdf": { key: "attachments/pdf", id: "pdf", section: "attachments", label: "PDF" },
  "attachments/word": { key: "attachments/word", id: "word", section: "attachments", label: "Word" },
  "attachments/zip": { key: "attachments/zip", id: "zip", section: "attachments", label: "ZIP" },
  "attachments/видео": { key: "attachments/видео", id: "видео", section: "attachments", label: "Видео" },
  "attachments/облако": { key: "attachments/облако", id: "облако", section: "attachments", label: "Облако" },
  "attachments/ссылка": { key: "attachments/ссылка", id: "ссылка", section: "attachments", label: "Ссылка" },
  "attachments/фото": { key: "attachments/фото", id: "фото", section: "attachments", label: "Фото" },
  "automation/ai": { key: "automation/ai", id: "ai", section: "automation", label: "AI" },
  "automation/workflow": { key: "automation/workflow", id: "workflow", section: "automation", label: "Workflow" },
  "automation/автоматизация": { key: "automation/автоматизация", id: "автоматизация", section: "automation", label: "Автоматизация" },
  "automation/интеграция": { key: "automation/интеграция", id: "интеграция", section: "automation", label: "Интеграция" },
  "automation/робот": { key: "automation/робот", id: "робот", section: "automation", label: "Робот" },
  "automation/триггер": { key: "automation/триггер", id: "триггер", section: "automation", label: "Триггер" },
  "candidate-hr/адрес": { key: "candidate-hr/адрес", id: "адрес", section: "candidate-hr", label: "Адрес" },
  "candidate-hr/гражданство": { key: "candidate-hr/гражданство", id: "гражданство", section: "candidate-hr", label: "Гражданство" },
  "candidate-hr/дата-рожд": { key: "candidate-hr/дата-рожд", id: "дата-рожд", section: "candidate-hr", label: "Дата рожд." },
  "candidate-hr/кат-прав": { key: "candidate-hr/кат-прав", id: "кат-прав", section: "candidate-hr", label: "Кат. прав" },
  "candidate-hr/навыки": { key: "candidate-hr/навыки", id: "навыки", section: "candidate-hr", label: "Навыки" },
  "candidate-hr/образование": { key: "candidate-hr/образование", id: "образование", section: "candidate-hr", label: "Образование" },
  "candidate-hr/опыт": { key: "candidate-hr/опыт", id: "опыт", section: "candidate-hr", label: "Опыт" },
  "candidate-hr/пол": { key: "candidate-hr/пол", id: "пол", section: "candidate-hr", label: "Пол" },
  "candidate-hr/разрешение": { key: "candidate-hr/разрешение", id: "разрешение", section: "candidate-hr", label: "Разрешение" },
  "candidate-hr/семья": { key: "candidate-hr/семья", id: "семья", section: "candidate-hr", label: "Семья" },
  "candidate-hr/человек": { key: "candidate-hr/человек", id: "человек", section: "candidate-hr", label: "Человек" },
  "candidate-hr/язык": { key: "candidate-hr/язык", id: "язык", section: "candidate-hr", label: "Язык" },
  "communication/email": { key: "communication/email", id: "email", section: "communication", label: "Email" },
  "communication/messenger": { key: "communication/messenger", id: "messenger", section: "communication", label: "Messenger" },
  "communication/sms": { key: "communication/sms", id: "sms", section: "communication", label: "SMS" },
  "communication/telegram": { key: "communication/telegram", id: "telegram", section: "communication", label: "Telegram" },
  "communication/whatsapp": { key: "communication/whatsapp", id: "whatsapp", section: "communication", label: "WhatsApp" },
  "communication/видео-звонок": { key: "communication/видео-звонок", id: "видео-звонок", section: "communication", label: "Видео звонок" },
  "communication/запись-звонка": { key: "communication/запись-звонка", id: "запись-звонка", section: "communication", label: "Запись звонка" },
  "communication/история": { key: "communication/история", id: "история", section: "communication", label: "История" },
  "communication/позвонить": { key: "communication/позвонить", id: "позвонить", section: "communication", label: "Позвонить" },
  "documents/id-карта": { key: "documents/id-карта", id: "id-карта", section: "documents", label: "ID карта" },
  "documents/ocr": { key: "documents/ocr", id: "ocr", section: "documents", label: "OCR" },
  "documents/pdf": { key: "documents/pdf", id: "pdf", section: "documents", label: "PDF" },
  "documents/архив": { key: "documents/архив", id: "архив", section: "documents", label: "Архив" },
  "documents/виза": { key: "documents/виза", id: "виза", section: "documents", label: "Виза" },
  "documents/внж": { key: "documents/внж", id: "внж", section: "documents", label: "ВНЖ" },
  "documents/документ": { key: "documents/документ", id: "документ", section: "documents", label: "Документ" },
  "documents/карта-побыту": { key: "documents/карта-побыту", id: "карта-побыту", section: "documents", label: "Карта побыту" },
  "documents/код-95": { key: "documents/код-95", id: "код-95", section: "documents", label: "Код 95" },
  "documents/медосмотр": { key: "documents/медосмотр", id: "медосмотр", section: "documents", label: "Медосмотр" },
  "documents/паспорт": { key: "documents/паспорт", id: "паспорт", section: "documents", label: "Паспорт" },
  "documents/подпись": { key: "documents/подпись", id: "подпись", section: "documents", label: "Подпись" },
  "documents/права-вод": { key: "documents/права-вод", id: "права-вод", section: "documents", label: "Права вод." },
  "documents/психотест": { key: "documents/психотест", id: "психотест", section: "documents", label: "Психотест" },
  "documents/сертификат": { key: "documents/сертификат", id: "сертификат", section: "documents", label: "Сертификат" },
  "documents/фото": { key: "documents/фото", id: "фото", section: "documents", label: "Фото" },
  "filters/filter": { key: "filters/filter", id: "filter", section: "filters", label: "Фильтр" },
  "filters/search": { key: "filters/search", id: "search", section: "filters", label: "Поиск" },
  "filters/вид": { key: "filters/вид", id: "вид", section: "filters", label: "Вид" },
  "filters/группировка": { key: "filters/группировка", id: "группировка", section: "filters", label: "Группировка" },
  "filters/канбан": { key: "filters/канбан", id: "канбан", section: "filters", label: "Канбан" },
  "filters/колонки": { key: "filters/колонки", id: "колонки", section: "filters", label: "Колонки" },
  "filters/сбросить": { key: "filters/сбросить", id: "сбросить", section: "filters", label: "Сбросить" },
  "filters/сортировка": { key: "filters/сортировка", id: "сортировка", section: "filters", label: "Сортировка" },
  "filters/сохр-вид": { key: "filters/сохр-вид", id: "сохр-вид", section: "filters", label: "Сохр. вид" },
  "filters/список": { key: "filters/список", id: "список", section: "filters", label: "Список" },
  "filters/таблица": { key: "filters/таблица", id: "таблица", section: "filters", label: "Таблица" },
  "fleet/gps": { key: "fleet/gps", id: "gps", section: "fleet", label: "GPS" },
  "fleet/авария": { key: "fleet/авария", id: "авария", section: "fleet", label: "Авария" },
  "fleet/автобус": { key: "fleet/автобус", id: "автобус", section: "fleet", label: "Автобус" },
  "fleet/грузовик": { key: "fleet/грузовик", id: "грузовик", section: "fleet", label: "Грузовик" },
  "fleet/карта": { key: "fleet/карта", id: "карта", section: "fleet", label: "Карта" },
  "fleet/ключ": { key: "fleet/ключ", id: "ключ", section: "fleet", label: "Ключ" },
  "fleet/колесо": { key: "fleet/колесо", id: "колесо", section: "fleet", label: "Колесо" },
  "fleet/легковой": { key: "fleet/легковой", id: "легковой", section: "fleet", label: "Легковой" },
  "fleet/маршрут": { key: "fleet/маршрут", id: "маршрут", section: "fleet", label: "Маршрут" },
  "fleet/прицеп": { key: "fleet/прицеп", id: "прицеп", section: "fleet", label: "Прицеп" },
  "fleet/пробег": { key: "fleet/пробег", id: "пробег", section: "fleet", label: "Пробег" },
  "fleet/сервис-то": { key: "fleet/сервис-то", id: "сервис-то", section: "fleet", label: "Сервис ТО" },
  "fleet/топливо": { key: "fleet/топливо", id: "топливо", section: "fleet", label: "Топливо" },
  "navigation-main-menu/api": { key: "navigation-main-menu/api", id: "api", section: "navigation-main-menu", label: "API" },
  "navigation-main-menu/calendar": { key: "navigation-main-menu/calendar", id: "calendar", section: "navigation-main-menu", label: "Календарь" },
  "navigation-main-menu/candidates": { key: "navigation-main-menu/candidates", id: "candidates", section: "navigation-main-menu", label: "Кандидаты" },
  "navigation-main-menu/documents": { key: "navigation-main-menu/documents", id: "documents", section: "navigation-main-menu", label: "Документы" },
  "navigation-main-menu/home": { key: "navigation-main-menu/home", id: "home", section: "navigation-main-menu", label: "Главная" },
  "navigation-main-menu/notifications": { key: "navigation-main-menu/notifications", id: "notifications", section: "navigation-main-menu", label: "Уведомления" },
  "navigation-main-menu/settings": { key: "navigation-main-menu/settings", id: "settings", section: "navigation-main-menu", label: "Настройки" },
  "navigation-main-menu/автоматизации": { key: "navigation-main-menu/автоматизации", id: "автоматизации", section: "navigation-main-menu", label: "Автоматизации" },
  "navigation-main-menu/автомобили": { key: "navigation-main-menu/автомобили", id: "автомобили", section: "navigation-main-menu", label: "Автомобили" },
  "navigation-main-menu/водители": { key: "navigation-main-menu/водители", id: "водители", section: "navigation-main-menu", label: "Водители" },
  "navigation-main-menu/доходы": { key: "navigation-main-menu/доходы", id: "доходы", section: "navigation-main-menu", label: "Доходы" },
  "navigation-main-menu/заказы": { key: "navigation-main-menu/заказы", id: "заказы", section: "navigation-main-menu", label: "Заказы" },
  "navigation-main-menu/инвойсы": { key: "navigation-main-menu/инвойсы", id: "инвойсы", section: "navigation-main-menu", label: "Инвойсы" },
  "navigation-main-menu/интеграции": { key: "navigation-main-menu/интеграции", id: "интеграции", section: "navigation-main-menu", label: "Интеграции" },
  "navigation-main-menu/клиенты": { key: "navigation-main-menu/клиенты", id: "клиенты", section: "navigation-main-menu", label: "Клиенты" },
  "navigation-main-menu/контракты": { key: "navigation-main-menu/контракты", id: "контракты", section: "navigation-main-menu", label: "Контракты" },
  "navigation-main-menu/легализация": { key: "navigation-main-menu/легализация", id: "легализация", section: "navigation-main-menu", label: "Легализация" },
  "navigation-main-menu/медосмотры": { key: "navigation-main-menu/медосмотры", id: "медосмотры", section: "navigation-main-menu", label: "Медосмотры" },
  "navigation-main-menu/мои-задачи": { key: "navigation-main-menu/мои-задачи", id: "мои-задачи", section: "navigation-main-menu", label: "Мои задачи" },
  "navigation-main-menu/мониторинг": { key: "navigation-main-menu/мониторинг", id: "мониторинг", section: "navigation-main-menu", label: "Мониторинг" },
  "navigation-main-menu/обращения": { key: "navigation-main-menu/обращения", id: "обращения", section: "navigation-main-menu", label: "Обращения" },
  "navigation-main-menu/обучение": { key: "navigation-main-menu/обучение", id: "обучение", section: "navigation-main-menu", label: "Обучение" },
  "navigation-main-menu/отделы": { key: "navigation-main-menu/отделы", id: "отделы", section: "navigation-main-menu", label: "Отделы" },
  "navigation-main-menu/отклики": { key: "navigation-main-menu/отклики", id: "отклики", section: "navigation-main-menu", label: "Отклики" },
  "navigation-main-menu/отпуска": { key: "navigation-main-menu/отпуска", id: "отпуска", section: "navigation-main-menu", label: "Отпуска" },
  "navigation-main-menu/отсутствия": { key: "navigation-main-menu/отсутствия", id: "отсутствия", section: "navigation-main-menu", label: "Отсутствия" },
  "navigation-main-menu/платежи": { key: "navigation-main-menu/платежи", id: "платежи", section: "navigation-main-menu", label: "Платежи" },
  "navigation-main-menu/подборы": { key: "navigation-main-menu/подборы", id: "подборы", section: "navigation-main-menu", label: "Подборы" },
  "navigation-main-menu/поломки": { key: "navigation-main-menu/поломки", id: "поломки", section: "navigation-main-menu", label: "Поломки" },
  "navigation-main-menu/пользователи": { key: "navigation-main-menu/пользователи", id: "пользователи", section: "navigation-main-menu", label: "Пользователи" },
  "navigation-main-menu/прицепы": { key: "navigation-main-menu/прицепы", id: "прицепы", section: "navigation-main-menu", label: "Прицепы" },
  "navigation-main-menu/расходы": { key: "navigation-main-menu/расходы", id: "расходы", section: "navigation-main-menu", label: "Расходы" },
  "navigation-main-menu/роли": { key: "navigation-main-menu/роли", id: "роли", section: "navigation-main-menu", label: "Роли" },
  "navigation-main-menu/сотрудники": { key: "navigation-main-menu/сотрудники", id: "сотрудники", section: "navigation-main-menu", label: "Сотрудники" },
  "navigation-main-menu/счета": { key: "navigation-main-menu/счета", id: "счета", section: "navigation-main-menu", label: "Счета" },
  "navigation-main-menu/тахографы": { key: "navigation-main-menu/тахографы", id: "тахографы", section: "navigation-main-menu", label: "Тахографы" },
  "navigation-main-menu/то": { key: "navigation-main-menu/то", id: "то", section: "navigation-main-menu", label: "ТО" },
  "navigation-main-menu/топливо": { key: "navigation-main-menu/топливо", id: "топливо", section: "navigation-main-menu", label: "Топливо" },
  "navigation-main-menu/услуги": { key: "navigation-main-menu/услуги", id: "услуги", section: "navigation-main-menu", label: "Услуги" },
  "navigation-main-menu/что-дальше": { key: "navigation-main-menu/что-дальше", id: "что-дальше", section: "navigation-main-menu", label: "Что дальше" },
  "navigation-main-menu/шины": { key: "navigation-main-menu/шины", id: "шины", section: "navigation-main-menu", label: "Шины" },
  "notifications/информация": { key: "notifications/информация", id: "информация", section: "notifications", label: "Информация" },
  "notifications/колокол": { key: "notifications/колокол", id: "колокол", section: "notifications", label: "Колокол" },
  "notifications/напоминание": { key: "notifications/напоминание", id: "напоминание", section: "notifications", label: "Напоминание" },
  "notifications/ошибка": { key: "notifications/ошибка", id: "ошибка", section: "notifications", label: "Ошибка" },
  "notifications/предупреждение": { key: "notifications/предупреждение", id: "предупреждение", section: "notifications", label: "Предупреждение" },
  "notifications/успех": { key: "notifications/успех", id: "успех", section: "notifications", label: "Успех" },
  "priority/critical": { key: "priority/critical", id: "critical", section: "priority", label: "Critical" },
  "priority/high": { key: "priority/high", id: "high", section: "priority", label: "High" },
  "priority/low": { key: "priority/low", id: "low", section: "priority", label: "Low" },
  "priority/medium": { key: "priority/medium", id: "medium", section: "priority", label: "Medium" },
  "sales/деньги": { key: "sales/деньги", id: "деньги", section: "sales", label: "Деньги" },
  "sales/договор": { key: "sales/договор", id: "договор", section: "sales", label: "Договор" },
  "sales/клиент-vip": { key: "sales/клиент-vip", id: "клиент-vip", section: "sales", label: "Клиент VIP" },
  "sales/компания": { key: "sales/компания", id: "компания", section: "sales", label: "Компания" },
  "sales/контакт": { key: "sales/контакт", id: "контакт", section: "sales", label: "Контакт" },
  "sales/кп": { key: "sales/кп", id: "кп", section: "sales", label: "КП" },
  "sales/оплата": { key: "sales/оплата", id: "оплата", section: "sales", label: "Оплата" },
  "sales/подписание": { key: "sales/подписание", id: "подписание", section: "sales", label: "Подписание" },
  "sales/сделка": { key: "sales/сделка", id: "сделка", section: "sales", label: "Сделка" },
  "sales/услуга": { key: "sales/услуга", id: "услуга", section: "sales", label: "Услуга" },
  "source-icons/api-source": { key: "source-icons/api-source", id: "api-source", section: "source-icons", label: "API Source" },
  "source-icons/crm": { key: "source-icons/crm", id: "crm", section: "source-icons", label: "CRM" },
  "source-icons/csv": { key: "source-icons/csv", id: "csv", section: "source-icons", label: "CSV" },
  "source-icons/email": { key: "source-icons/email", id: "email", section: "source-icons", label: "Email" },
  "source-icons/facebook": { key: "source-icons/facebook", id: "facebook", section: "source-icons", label: "Facebook" },
  "source-icons/google-ads": { key: "source-icons/google-ads", id: "google-ads", section: "source-icons", label: "Google Ads" },
  "source-icons/google-maps": { key: "source-icons/google-maps", id: "google-maps", section: "source-icons", label: "Google Maps" },
  "source-icons/google-search": { key: "source-icons/google-search", id: "google-search", section: "source-icons", label: "Google Search" },
  "source-icons/import-file": { key: "source-icons/import-file", id: "import-file", section: "source-icons", label: "Import File" },
  "source-icons/instagram": { key: "source-icons/instagram", id: "instagram", section: "source-icons", label: "Instagram" },
  "source-icons/internal": { key: "source-icons/internal", id: "internal", section: "source-icons", label: "Internal" },
  "source-icons/landing-page": { key: "source-icons/landing-page", id: "landing-page", section: "source-icons", label: "Landing Page" },
  "source-icons/linkedin": { key: "source-icons/linkedin", id: "linkedin", section: "source-icons", label: "LinkedIn" },
  "source-icons/manual": { key: "source-icons/manual", id: "manual", section: "source-icons", label: "Manual" },
  "source-icons/messenger": { key: "source-icons/messenger", id: "messenger", section: "source-icons", label: "Messenger" },
  "source-icons/meta": { key: "source-icons/meta", id: "meta", section: "source-icons", label: "Meta Ads" },
  "source-icons/phone": { key: "source-icons/phone", id: "phone", section: "source-icons", label: "Phone" },
  "source-icons/qr-code": { key: "source-icons/qr-code", id: "qr-code", section: "source-icons", label: "QR Code" },
  "source-icons/recommendation": { key: "source-icons/recommendation", id: "recommendation", section: "source-icons", label: "Recommendation" },
  "source-icons/referral": { key: "source-icons/referral", id: "referral", section: "source-icons", label: "Referral" },
  "source-icons/sms": { key: "source-icons/sms", id: "sms", section: "source-icons", label: "SMS" },
  "source-icons/telegram": { key: "source-icons/telegram", id: "telegram", section: "source-icons", label: "Telegram" },
  "source-icons/tiktok": { key: "source-icons/tiktok", id: "tiktok", section: "source-icons", label: "TikTok" },
  "source-icons/viber": { key: "source-icons/viber", id: "viber", section: "source-icons", label: "Viber" },
  "source-icons/website": { key: "source-icons/website", id: "website", section: "source-icons", label: "Website" },
  "source-icons/whatsapp": { key: "source-icons/whatsapp", id: "whatsapp", section: "source-icons", label: "WhatsApp" },
  "source-icons/youtube": { key: "source-icons/youtube", id: "youtube", section: "source-icons", label: "YouTube" },
  "status/архив": { key: "status/архив", id: "архив", section: "status", label: "Архив" },
  "status/в-работе": { key: "status/в-работе", id: "в-работе", section: "status", label: "В работе" },
  "status/важно": { key: "status/важно", id: "важно", section: "status", label: "Важно" },
  "status/заблокировано": { key: "status/заблокировано", id: "заблокировано", section: "status", label: "Заблокировано" },
  "status/завершено": { key: "status/завершено", id: "завершено", section: "status", label: "Завершено" },
  "status/новый": { key: "status/новый", id: "новый", section: "status", label: "Новый" },
  "status/ожидает": { key: "status/ожидает", id: "ожидает", section: "status", label: "Ожидает" },
  "status/ошибка": { key: "status/ошибка", id: "ошибка", section: "status", label: "Ошибка" },
  "status/просрочено": { key: "status/просрочено", id: "просрочено", section: "status", label: "Просрочено" },
  "status/черновик": { key: "status/черновик", id: "черновик", section: "status", label: "Черновик" },
  "system/api": { key: "system/api", id: "api", section: "system", label: "API" },
  "system/company": { key: "system/company", id: "company", section: "system", label: "Company" },
  "system/database": { key: "system/database", id: "database", section: "system", label: "Database" },
  "system/module": { key: "system/module", id: "module", section: "system", label: "Module" },
  "system/security": { key: "system/security", id: "security", section: "system", label: "Security" },
  "system/shield": { key: "system/shield", id: "shield", section: "system", label: "Shield" },
  "system/sync": { key: "system/sync", id: "sync", section: "system", label: "Sync" },
  "system/tenant": { key: "system/tenant", id: "tenant", section: "system", label: "Tenant" },
  "system/workspace": { key: "system/workspace", id: "workspace", section: "system", label: "Workspace" },
  "system/мониторинг": { key: "system/мониторинг", id: "мониторинг", section: "system", label: "Мониторинг" },
  "system/пользователь": { key: "system/пользователь", id: "пользователь", section: "system", label: "Пользователь" },
  "time/calendar": { key: "time/calendar", id: "calendar", section: "time", label: "Календарь" },
  "time/завтра": { key: "time/завтра", id: "завтра", section: "time", label: "Завтра" },
  "time/история": { key: "time/история", id: "история", section: "time", label: "История" },
  "time/просрочено": { key: "time/просрочено", id: "просрочено", section: "time", label: "Просрочено" },
  "time/сегодня": { key: "time/сегодня", id: "сегодня", section: "time", label: "Сегодня" },
  "time/таймер": { key: "time/таймер", id: "таймер", section: "time", label: "Таймер" },
  "time/часы": { key: "time/часы", id: "часы", section: "time", label: "Часы" },
  "workflow/выполнено": { key: "workflow/выполнено", id: "выполнено", section: "workflow", label: "Выполнено" },
  "workflow/заблокировано": { key: "workflow/заблокировано", id: "заблокировано", section: "workflow", label: "Заблокировано" },
  "workflow/конвертировать": { key: "workflow/конвертировать", id: "конвертировать", section: "workflow", label: "Конвертировать" },
  "workflow/на-проверке": { key: "workflow/на-проверке", id: "на-проверке", section: "workflow", label: "На проверке" },
  "workflow/назначить": { key: "workflow/назначить", id: "назначить", section: "workflow", label: "Назначить" },
  "workflow/ожидание": { key: "workflow/ожидание", id: "ожидание", section: "workflow", label: "Ожидание" },
  "workflow/отклонено": { key: "workflow/отклонено", id: "отклонено", section: "workflow", label: "Отклонено" },
  "workflow/передать": { key: "workflow/передать", id: "передать", section: "workflow", label: "Передать" },
  "workflow/подтверждено": { key: "workflow/подтверждено", id: "подтверждено", section: "workflow", label: "Подтверждено" },
  "workflow/следующий-шаг": { key: "workflow/следующий-шаг", id: "следующий-шаг", section: "workflow", label: "Следующий шаг" },
  "workflow/требует-внимания": { key: "workflow/требует-внимания", id: "требует-внимания", section: "workflow", label: "Требует внимания" },
} as const satisfies Record<UiIconKey, UiIconRecord>

export const UI_ICON_ALIASES = {
  "ai": "automation/ai",
  "api": "navigation-main-menu/api",
  "api-source": "source-icons/api-source",
  "calendar": "navigation-main-menu/calendar",
  "candidates": "navigation-main-menu/candidates",
  "company": "system/company",
  "critical": "priority/critical",
  "crm": "source-icons/crm",
  "csv": "source-icons/csv",
  "database": "system/database",
  "documents": "navigation-main-menu/documents",
  "email": "communication/email",
  "excel": "attachments/excel",
  "facebook": "source-icons/facebook",
  "filter": "filters/filter",
  "funnel": "analytics/funnel",
  "google-ads": "source-icons/google-ads",
  "google-maps": "source-icons/google-maps",
  "google-search": "source-icons/google-search",
  "gps": "fleet/gps",
  "high": "priority/high",
  "home": "navigation-main-menu/home",
  "id-карта": "documents/id-карта",
  "import-file": "source-icons/import-file",
  "instagram": "source-icons/instagram",
  "internal": "source-icons/internal",
  "kpi": "analytics/kpi",
  "landing-page": "source-icons/landing-page",
  "linkedin": "source-icons/linkedin",
  "low": "priority/low",
  "manual": "source-icons/manual",
  "medium": "priority/medium",
  "messenger": "communication/messenger",
  "meta": "source-icons/meta",
  "module": "system/module",
  "notifications": "navigation-main-menu/notifications",
  "ocr": "documents/ocr",
  "pdf": "documents/pdf",
  "phone": "source-icons/phone",
  "qr-code": "source-icons/qr-code",
  "recommendation": "source-icons/recommendation",
  "referral": "source-icons/referral",
  "search": "filters/search",
  "security": "system/security",
  "settings": "navigation-main-menu/settings",
  "shield": "system/shield",
  "sms": "communication/sms",
  "sync": "system/sync",
  "telegram": "communication/telegram",
  "tenant": "system/tenant",
  "tiktok": "source-icons/tiktok",
  "viber": "source-icons/viber",
  "website": "source-icons/website",
  "whatsapp": "communication/whatsapp",
  "word": "attachments/word",
  "workflow": "automation/workflow",
  "workspace": "system/workspace",
  "youtube": "source-icons/youtube",
  "zip": "attachments/zip",
  "авария": "fleet/авария",
  "автобус": "fleet/автобус",
  "автоматизации": "navigation-main-menu/автоматизации",
  "автоматизация": "automation/автоматизация",
  "автомобили": "navigation-main-menu/автомобили",
  "адрес": "candidate-hr/адрес",
  "архив": "documents/архив",
  "архивировать": "actions/архивировать",
  "в-работе": "status/в-работе",
  "важно": "status/важно",
  "вид": "filters/вид",
  "видео": "attachments/видео",
  "видео-звонок": "communication/видео-звонок",
  "виза": "documents/виза",
  "внж": "documents/внж",
  "водители": "navigation-main-menu/водители",
  "выполнено": "workflow/выполнено",
  "гражданство": "candidate-hr/гражданство",
  "график": "analytics/график",
  "грузовик": "fleet/грузовик",
  "группировка": "filters/группировка",
  "далее": "actions/далее",
  "дата-рожд": "candidate-hr/дата-рожд",
  "деньги": "sales/деньги",
  "договор": "sales/договор",
  "документ": "documents/документ",
  "доходы": "navigation-main-menu/доходы",
  "дублировать": "actions/дублировать",
  "заблокировано": "workflow/заблокировано",
  "завершено": "status/завершено",
  "завтра": "time/завтра",
  "загрузить": "actions/загрузить",
  "заказы": "navigation-main-menu/заказы",
  "закрыть": "actions/закрыть",
  "запись-звонка": "communication/запись-звонка",
  "импорт": "actions/импорт",
  "инвойсы": "navigation-main-menu/инвойсы",
  "интеграции": "navigation-main-menu/интеграции",
  "интеграция": "automation/интеграция",
  "информация": "notifications/информация",
  "история": "communication/история",
  "канбан": "filters/канбан",
  "карта": "fleet/карта",
  "карта-побыту": "documents/карта-побыту",
  "кат-прав": "candidate-hr/кат-прав",
  "клиент-vip": "sales/клиент-vip",
  "клиенты": "navigation-main-menu/клиенты",
  "ключ": "fleet/ключ",
  "код-95": "documents/код-95",
  "колесо": "fleet/колесо",
  "колокол": "notifications/колокол",
  "колонки": "filters/колонки",
  "компания": "sales/компания",
  "конверсия": "analytics/конверсия",
  "конвертировать": "workflow/конвертировать",
  "контакт": "sales/контакт",
  "контракты": "navigation-main-menu/контракты",
  "копировать": "actions/копировать",
  "кп": "sales/кп",
  "легализация": "navigation-main-menu/легализация",
  "легковой": "fleet/легковой",
  "маршрут": "fleet/маршрут",
  "медосмотр": "documents/медосмотр",
  "медосмотры": "navigation-main-menu/медосмотры",
  "мои-задачи": "navigation-main-menu/мои-задачи",
  "мониторинг": "navigation-main-menu/мониторинг",
  "на-проверке": "workflow/на-проверке",
  "навыки": "candidate-hr/навыки",
  "назад": "actions/назад",
  "назначить": "workflow/назначить",
  "напоминание": "notifications/напоминание",
  "новый": "status/новый",
  "облако": "attachments/облако",
  "обновить": "actions/обновить",
  "образование": "candidate-hr/образование",
  "обращения": "navigation-main-menu/обращения",
  "обучение": "navigation-main-menu/обучение",
  "ожидает": "status/ожидает",
  "ожидание": "workflow/ожидание",
  "оплата": "sales/оплата",
  "опыт": "candidate-hr/опыт",
  "отделы": "navigation-main-menu/отделы",
  "отклики": "navigation-main-menu/отклики",
  "отклонено": "workflow/отклонено",
  "открыть": "actions/открыть",
  "отпуска": "navigation-main-menu/отпуска",
  "отсутствия": "navigation-main-menu/отсутствия",
  "ошибка": "status/ошибка",
  "падение": "analytics/падение",
  "паспорт": "documents/паспорт",
  "передать": "workflow/передать",
  "печать": "actions/печать",
  "платежи": "navigation-main-menu/платежи",
  "подборы": "navigation-main-menu/подборы",
  "поделиться": "actions/поделиться",
  "подписание": "sales/подписание",
  "подпись": "documents/подпись",
  "подтверждено": "workflow/подтверждено",
  "позвонить": "communication/позвонить",
  "пол": "candidate-hr/пол",
  "поломки": "navigation-main-menu/поломки",
  "пользователи": "navigation-main-menu/пользователи",
  "пользователь": "system/пользователь",
  "права-вод": "documents/права-вод",
  "предупреждение": "notifications/предупреждение",
  "прицеп": "fleet/прицеп",
  "прицепы": "navigation-main-menu/прицепы",
  "пробег": "fleet/пробег",
  "просрочено": "status/просрочено",
  "психотест": "documents/психотест",
  "разрешение": "candidate-hr/разрешение",
  "расходы": "navigation-main-menu/расходы",
  "редактировать": "actions/редактировать",
  "робот": "automation/робот",
  "роли": "navigation-main-menu/роли",
  "рост": "analytics/рост",
  "сбросить": "filters/сбросить",
  "сделка": "sales/сделка",
  "сегодня": "time/сегодня",
  "семья": "candidate-hr/семья",
  "сервис-то": "fleet/сервис-то",
  "сертификат": "documents/сертификат",
  "скачать": "actions/скачать",
  "следующий-шаг": "workflow/следующий-шаг",
  "создать": "actions/создать",
  "сортировка": "filters/сортировка",
  "сотрудники": "navigation-main-menu/сотрудники",
  "сохр-вид": "filters/сохр-вид",
  "сохранить": "actions/сохранить",
  "список": "filters/список",
  "ссылка": "attachments/ссылка",
  "статистика": "analytics/статистика",
  "счета": "navigation-main-menu/счета",
  "таблица": "filters/таблица",
  "таймер": "time/таймер",
  "тахографы": "navigation-main-menu/тахографы",
  "то": "navigation-main-menu/то",
  "топливо": "navigation-main-menu/топливо",
  "требует-внимания": "workflow/требует-внимания",
  "триггер": "automation/триггер",
  "удалить": "actions/удалить",
  "услуга": "sales/услуга",
  "услуги": "navigation-main-menu/услуги",
  "успех": "notifications/успех",
  "фото": "documents/фото",
  "часы": "time/часы",
  "человек": "candidate-hr/человек",
  "черновик": "status/черновик",
  "что-дальше": "navigation-main-menu/что-дальше",
  "шины": "navigation-main-menu/шины",
  "экспорт": "actions/экспорт",
  "язык": "candidate-hr/язык",
} as const satisfies Record<UiIconAliasId, UiIconKey>

export const UI_ICON_KEYS = Object.keys(UI_ICONS) as UiIconKey[]

export function resolveUiIconKey(id: UiIconId): UiIconKey {
  if (Object.prototype.hasOwnProperty.call(UI_ICONS, id)) return id as UiIconKey
  if (Object.prototype.hasOwnProperty.call(UI_ICON_ALIASES, id)) {
    return UI_ICON_ALIASES[id as UiIconAliasId]
  }
  throw new Error(`Unknown UI icon id: ${id}`)
}

export function isUiIconId(value: string): value is UiIconId {
  return Object.prototype.hasOwnProperty.call(UI_ICONS, value)
    || Object.prototype.hasOwnProperty.call(UI_ICON_ALIASES, value)
}

export type UiIconTheme = 'light' | 'dark'

export function resolveUiIconUrl(id: UiIconId, theme: UiIconTheme = 'light'): string {
  const record = UI_ICONS[resolveUiIconKey(id)]
  return `/assets/icons/${theme}/ui/${record.section}/${record.id}.svg`
}

